[[plugins]] 
repo = 'Shougo/dein.vim' 

[[plugins]] 
repo = 'Shougo/vimproc.vim' 
build = 'make' 

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'kana/vim-textobj-function' 

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'fuenor/JpFormat.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'  

[[plugins]]
repo = 'kana/vim-operator-user' 

[[plugins]]
repo = 'tyru/operator-camelize.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'vim-scripts/taglist.vim' 

#[[plugins]]
#repo = 'vim-syntastic/syntastic'

#[[plugins]]
#repo = 'maksimr/vim-jsbeautify'

#[[plugins]]
#repo = 'rhysd/vim-clang-format.git'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/louver.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jremmen/vim-ripgrep'

[[plugins]]
repo = 'LeafCage/foldCC.vim'
