[[plugins]] 
repo = 'Shougo/dein.vim' 
rtp = '' 

[[plugins]] 
repo = 'Shougo/vimproc.vim' 
build = 'make' 

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'kana/vim-textobj-function' 

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'fuenor/JpFormat.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tyru/open-browser.vim'


[[plugins]]
repo = 'kana/vim-textobj-user'  

[[plugins]]
repo = 'kana/vim-operator-user' 


#[[plugins]]
# repo = 'rhysd/vim-clang-format.git', { 'rev' : 'b84a2a8' }
#repo = 'rhysd/vim-clang-format.git'
#rev = 'b84a2a819'


#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#
#[[plugins]]
#repo = 'vim-airline/vim-airline'
#

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-scripts/louver.vim'

